export const boardMembers = [
  {
    id: 1,
    role: '회장',
    name: '이상영 (18학번)',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 2,
    role: '부회장',
    name: '박유민 (21학번)',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 3,
    role: '학습부장',
    name: '박상빈 (20학번)',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 4,
    role: '회계부장',
    name: '조은진 (23학번)',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 5,
    role: '홍보부장',
    name: '김예원 (23학번)',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 6,
    role: '학습부',
    name: '이승빈 (24학번)',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 7,
    role: '홍보부',
    name: '000 (25학번)',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
];
