/** 조직도 및 개발팀 데이터 */

export const boardMembers = [
  {
    id: 1,
    role: '회장',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 2,
    role: '회장',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 3,
    role: '회장',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 4,
    role: '회장',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 5,
    role: '회장',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 6,
    role: '회장',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 7,
    role: '회장',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 8,
    role: '회장',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
];

export const boardDevelopers = [
  {
    id: 1,
    role: '개발팀 팀장',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 2,
    role: '개발팀 팀원',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 3,
    role: '개발팀 팀원',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 4,
    role: '개발팀 팀원',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 5,
    role: '개발팀 팀원',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
  },
  {
    id: 6,
    role: '개발팀 팀원',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 7,
    role: '개발팀 팀원',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 8,
    role: '개발팀 팀원',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
  {
    id: 9,
    role: '개발팀 팀원',
    name: '이름 홍길동',
    student_id: '00000000',
    profile_image: '',
    bio: '',
  },
];
